### ISSUE TITLE
Parameterized Queries using 2 or more parameters

### ISSUE THREAD

**Issue by francot** [epantry/django-sql-explorer#118]
Make it possible to use 2 or more paramters for Parameterized Queries.
For Example
'SELECT * FROM table WHERE id=$$id$$ AND date >= $$date$$'

**Comment by chrisclark** [comment]
Hi @francot -- this is totally supported. What's happening when you try it? Explorer should build mutiple text boxes for the different params. I just tested this on my install and all seems well.

**Comment by francot** [comment]
Hi @chrisclark you have right. It works.  
This error: 
```syntax error at or near "and" LINE 1: ..T * FROM table WHERE id = AND date ... ^ ```
confused me. I have 2 box for the parameter despite the error.

I note that parametric query always return error if the field is not a char type.
for example using 1 parameter:
``` 'SELECT * FROM table WHERE date = $$date$$'```
return 
```syntax error at end of input LINE 1: SELECT * FROM table WHERE date  = ^ ```

Anyway I can view the Box.
Why it returns error?



Thanks
f

**Comment by chrisclark** [comment]
Yep -- Explorer will try to execute the query no matter what, and of course parameters are invalid SQL (if they aren't quoted) so it returns an error. For a time I had explorer not execute the query at all of parameters were present, but I felt it was more useful to execute it so that, if your parameters were quoted, you could at least figure out if the rest of your SQL was valid.

If you can make a good case for different behavior, I'm happy to consider it. Thanks!
