### ISSUE TITLE
Conflict when doing initial migration

### ISSUE THREAD

**Issue by mdamien** [epantry/django-sql-explorer#147]
Hi, with `django 1.8`, I get this error when running `syncdb`:

```
explorer.Query.created_by_user: (fields.E304) Reverse accessor for 'Query.created_by_user' clashes with reverse accessor for 'Query.last_executed_by'.
	HINT: Add or change a related_name argument to the definition for 'Query.created_by_user' or 'Query.last_executed_by'.
rosemeta.Query.last_executed_by: (fields.E304) Reverse accessor for 'Query.last_executed_by' clashes with reverse accessor for 'Query.created_by_user'.
	HINT: Add or change a related_name argument to the definition for 'Query.last_executed_by' or 'Query.created_by_user'.
```

Maybe I'm doing something wrong, just wanted to let you know.

EDIT: Fixed it by adding a `related_name` attribute to the `created_by_user` attribute of `Query`. Can do a PR

**Comment by chrisclark** [comment]
thanks @mdamien -- looks like this is a conflict with another Django app called rosemeta that happens to use the same model name. I don't think I'm going to change the related name since this is specific to your install. Appreciate the issue being filed nonetheless.

p.s. If anyone thinks I'm wrong and should use some kind of vendor-specific related name, feel free to chime in.

**Comment by mdamien** [comment]
Oops, thanks a lot.
