### ISSUE TITLE
Explorer index page not working on Django 1.9

### ISSUE THREAD

**Issue by grantmcconnaughey** [epantry/django-sql-explorer#178]
I'm having trouble getting the index page at `/explorer/` to work on Django 1.9.1. Here's the error:

```
Request Method:	GET
Request URL:	http://localhost:8000/explorer/
Django Version:	1.9.1
Exception Type:	ProgrammingError
Exception Value:	
column "explorer_query.title" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "explorer_query"."id", "explorer_query"."title", "exp...
```

The error is with the queryset on `ListQueryView`. The queryset it is returning is `Query.objects.prefetch_related('created_by_user').all().annotate(run_count=Count('querylog'))`. I fired up a Django shell and ran the following to see what query is being generated (I formatted the SQL for readability):

```
In [1]: from explorer.views import ListQueryView

In [2]: from django.test.client import RequestFactory

In [3]: request = RequestFactory()

In [4]: user = User.objects.first()

In [5]: request.user = user

In [6]: view = ListQueryView()

In [7]: view.request = request

In [8]: print view.get_queryset().query
SELECT "explorer_query"."id", 
       "explorer_query"."title", 
       "explorer_query"."sql", 
       "explorer_query"."description", 
       "explorer_query"."created_by_user_id", 
       "explorer_query"."created_at", 
       "explorer_query"."last_run_date", 
       "explorer_query"."snapshot", 
       Count("explorer_querylog"."id") AS "run_count" 
FROM   "explorer_query" 
       LEFT OUTER JOIN "explorer_querylog" 
                    ON ( "explorer_query"."id" = 
                       "explorer_querylog"."query_id" ) 
GROUP  BY "explorer_query"."id" 
ORDER  BY "explorer_query"."title" ASC 
```

Sure enough, only `explorer_query.id` is in the GROUP BY clause. Here's the result of me running the same code on Django 1.8.8 (formatted for readability):

```
SELECT "explorer_query"."id", 
       "explorer_query"."title", 
       "explorer_query"."sql", 
       "explorer_query"."description", 
       "explorer_query"."created_by_user_id", 
       "explorer_query"."created_at", 
       "explorer_query"."last_run_date", 
       "explorer_query"."snapshot", 
       Count("explorer_querylog"."id") AS "run_count" 
FROM   "explorer_query" 
       LEFT OUTER JOIN "explorer_querylog" 
                    ON ( "explorer_query"."id" = "explorer_querylog"."query_id" ) 
GROUP  BY "explorer_query"."id", 
          "explorer_query"."title", 
          "explorer_query"."sql", 
          "explorer_query"."description", 
          "explorer_query"."created_by_user_id", 
          "explorer_query"."created_at", 
          "explorer_query"."last_run_date", 
          "explorer_query"."snapshot" 
ORDER  BY "explorer_query"."title" ASC 
```

All of the fields are in the GROUP BY clause now. I don't know if this is an issue with the SQL building in Django 1.9, or if something changed.

**Comment by grantmcconnaughey** [comment]
I filed a bug report on the off chance this is a bug in Django. https://code.djangoproject.com/ticket/26148

**Comment by chrisclark** [comment]
Coincidentally, I'm familiar with this issue (though not from anything related to Explorer) -- what version of what DB are you using? 

It's actually a super interesting issue that I didn't realized was addressed in 1.9:

https://code.djangoproject.com/ticket/19259

Basically, annotate() has historically produced inefficient SQL because it does a 'group by' on EVERY field of EVERY table in the join, instead of just grouping on the selected columns.

There's a flag in the SQL generator for MySQL that will instead produce "group by *" for that DB because mysql supports that optimization. With Postgres, the optimized sql (shorthand for "group by everything in the table") is not *, but rather <table>.<primary_key>. However this was super hard to implement in the past (I tried...) because at the point when the group_by statement is built, the generator doesn't have knowledge of which entities are being joined and what their primary keys are.

Looks like the 'pathological group by' issue has been addressed for Postgres in 1.9 however, which accounts for the differing SQL. I believe this syntax was new to Postgres 9, however, so you might get this error if you are running an old postgres version. Just a guess.

**Comment by chrisclark** [comment]
Looking at the actual fix: https://github.com/django/django/commit/dc27f3ee0c3eb9bb17d6cb764788eeaf73a371d7

It looks like, if this is a bug, it's due to incorrect DB feature detection. Django is detecting that your db supports "allows_group_by_selected_pks", but apparently it does not.

**Comment by grantmcconnaughey** [comment]
Wow, I'm glad you're so familiar with it! I think it is a Postgres issue. When using Postgres 9.3 it works just fine. When using Postgres 9.0 it breaks. I guess I'm going to have to upgrade Postgres versions before I can go to Django 1.9. Or I could just monkey patch `allows_group_by_selected_pks` for now... Just don't tell anyone. 🙈🙉🙊

**Comment by chrisclark** [comment]
I'm going to close this issue because it appears to be Django-related and, at worst, fixable by upgrading postgres. Thanks for the fun report!
